name: Docker Build & Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Setup SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 2️⃣ Build and deploy Docker on server
      - name: Build & Deploy Docker on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p /home/${{ secrets.SSH_USERNAME }}/deploy-app
            cd /home/${{ secrets.SSH_USER }}/deploy-app

            # Stop old container & remove old image
            docker stop react-devops-app || true
            docker rm react-devops-app || true
            docker rmi react-devops-app:latest || true
          EOF

          # Copy Dockerfile and project files
          scp -i ~/.ssh/id_rsa -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/deploy-app/

          # Build and run Docker container on server
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USER }}/deploy-app
            docker build -t react-devops-app:latest .
            docker run -d -p 8080:80 --name react-devops-app react-devops-app:latest
          EOF
